config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'catalogs#index'

  resources :catalogs, only: [:index] do
  end

  resources :guest_books do
    collection do
      get 'search'
    end
  end

  resources :book_types do
    collection do
      get 'search'
    end
  end

  resources :books do
    member do
      get 'generate_barcode'
    end
    collection do
      get 'search'
    end
  end

  resources :catalogs do
    collection do
      get 'search'
    end
  end

  resources :dashboard, only: [:index]

  resources :theses do
    collection do
      get 'search'
    end
  end

  resources :members do
    member do
      get 'generate_card'
    end
    collection do
      get 'search'
      get 'download'
    end
  end

  resources :return_books, only: [:index] do
    collection do
      get 'search'
    end
  end

  resources :borrow_books, only: [:index, :new, :create] do
    resources :return_books

    collection do
      get 'search'
      get 'validate_borrow_books'
      get 'validate_return_date'
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader

	belongs_to	:book_type

	has_many :borrow_books

	scope :searching, lambda{ |query| where("book_code like :keyword OR title like :keyword OR author like :keyword OR publisher like :keyword OR yop like :keyword OR resource like :keyword", { keyword: "%#{query}%" }) unless query.blank? }

	validates :isbn, length: { minimum: 13, maximum: 13 }

	after_create :prepare_number

	def prepare_number
		BookNumber.generate_number(self)
	end

	def generate_barcode
		require 'barby/barcode/code_128'
		require 'barby/outputter/cairo_outputter'

		barcode = Barby::Code128B.new(self.isbn)
		save_path = Rails.root.join('public', 'downloads', 'barcode', 'books',"#{self.isbn}.png")
		File.open(save_path, 'w'){|f| f.write barcode.to_png }
	end
end

app/models/book_number.rb
class BookNumber < ActiveRecord::Base
	def self.generate_number(object)
		# set class name of data to be manipulated
		class_name = object.class.to_s

	    type = object.book_type_id
	    year = object.yop? ? object.yop : Time.now.year

	    conditions =  ["book_type_id = ? AND year = ?", type, year]

	    # Find Or Create
	    book_number = self.where(conditions).first || self.create!({book_type_id: type, year: year})
	    # Increase form number
	    current_number = book_number.current_number + 1

	    # Create Static Length Number i.e 0001
	    number = current_number.to_s.split('')
	    number.map { |value|
	      number.unshift(0) if number.count < 4
	    }

	    book_type = type.to_s.split('')
	    book_type.map { |value|
	      book_type.unshift(0) if book_type.count < 2
	    }

	    if object.update_attribute(:book_code, "#{book_type.join('')}#{year}#{number.join('')}") #set form number
	      # update current number
	      book_number.update_attribute(:current_number, current_number)
	    end
	end
end

app/models/book_type.rb
class BookType < ActiveRecord::Base
	has_many :books
end

app/models/borrow_book.rb
class BorrowBook < ActiveRecord::Base
	MAXBOOK = 2

	belongs_to :member
	belongs_to :user
	belongs_to :book

	has_one :return_book

	scope :searching, lambda{ |query| where(borrow_code: query) }
end

app/models/guest_book.rb
class GuestBook < ActiveRecord::Base
	scope :of_day, lambda { where("YEAR(date) = '#{Time.now.year}' AND MONTH(date) = '#{Time.now.month}' AND DAY(date) = '#{Time.now.day}'") }
	scope :searching, lambda{ |query| where("`name` like :keyword OR `from` like :keyword OR `necessary` like :keyword", { keyword: "%#{query}%" }) }
end

app/models/member.rb
class Member < ActiveRecord::Base
	CONTAINER_DIR = File.join(Rails.public_path, "downloads")

	has_many :borrow_books

	scope :searching, lambda{ |query| where("nim like :keyword OR firstname like :keyword OR lastname like :keyword", { keyword: "%#{query}%" }) unless query.blank? }

	def self.import_all
		unless File.directory? CONTAINER_DIR #~> check if container dir exist
	      Dir.mkdir CONTAINER_DIR, 0755
	    end

		require 'spreadsheet'

		Spreadsheet.client_encoding = 'UTF-8'

		members_file = Spreadsheet::Workbook.new
		members_file_sheet1 = members_file.create_worksheet

		members_file_sheet1[0,0] = "NIM"
		members_file_sheet1[0,1] = "Nama"
		members_file_sheet1[0,2] = "Tempat Lahir"
		members_file_sheet1[0,3] = "Tanggal Lahir"
		members_file_sheet1[0,4] = "Jenis Kelamin"
		members_file_sheet1[0,5] = "Alamat"
		members_file_sheet1[0,6] = "Telepon"
		members_file_sheet1[0,7] = "Masa Aktif"
		members_file_sheet1[0,8] = "Status"

		index = 1
		Member.all.each do |member|
			members_file_sheet1[index,0] = member.nim
			members_file_sheet1[index,1] = "#{member.firstname} #{member.lastname}"
			members_file_sheet1[index,2] = member.pob
			members_file_sheet1[index,3] = member.dob
			members_file_sheet1[index,4] = member.gender
			members_file_sheet1[index,5] = member.address
			members_file_sheet1[index,6] = member.phone
			members_file_sheet1[index,7] = member.active_period
			members_file_sheet1[index,8] = member.status? ? "Aktif" : "Non Aktif"

			index += 1
		end

		path_file = File.join(CONTAINER_DIR, "daftar_anggota.xls")
		members_file.write path_file
	end

	def generate_barcode
		require 'barby/barcode/code_128'
		require 'barby/outputter/cairo_outputter'

		barcode = Barby::Code128B.new(self.nim)
		save_path = Rails.root.join('public', 'downloads', 'barcode', 'members',"#{self.nim}.png")
		File.open(save_path, 'w'){|f| f.write barcode.to_png }
	end
end

app/models/return_book.rb
class ReturnBook < ActiveRecord::Base
	belongs_to :borrow_book
end

app/models/thesis.rb
class Thesis < ActiveRecord::Base
	CATEGORY = [["RPL", "RPL"],["SI", "SI"],["APLIKASI", "APLIKASI"],["SIMULASI", "SIMULASI"]]
	KIND = [["TUGAS AKHIR", "TA"],["LAPORAN KERJA PRAKTEK", "LKP"]]

	scope :searching, lambda{ |query| where("thesis_code like :keyword OR year like	:keyword OR title like :keyword OR category like :keyword", { keyword: "%#{query}%" }) unless query.blank? }

	after_create :prepare_number

	def prepare_number
		ThesisNumber.generate_number(self)
	end
end

app/models/thesis_number.rb
class ThesisNumber < ActiveRecord::Base
	def self.generate_number(object)
		# set class name of data to be manipulated
		class_name = object.class.to_s

	    kind = object.kind
	    year = object.year
	    category = object.category

	    conditions =  ["kind = ? AND year = ? AND category = ?", kind, year, category]

	    # Find Or Create
	    thesis_number = self.where(conditions).first || self.create!({kind: kind, year: year, category: category})
	    # Increase form number
	    current_number = thesis_number.current_number + 1

	    # Create Static Length Number i.e 0001
	    number = current_number.to_s.split('')
	    number.map { |value|
	      number.unshift(0) if number.count < 4
	    }

	    if object.update_attribute(:thesis_code, "#{kind}/#{year}/#{category}/#{number.join('')}") #set form number
	      # update current number
	      thesis_number.update_attribute(:current_number, current_number)
	    end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :borrow_books
end

app/helpers/application_helper.rb
module ApplicationHelper
	def amount_fine(borrow_book)
		if Time.now > borrow_book.return_date
			(Time.now.to_date - borrow_book.return_date.to_date).to_i * borrow_book.book.book_type.fine_per_day
		else
			0
		end
	end

	def late(borrow_book)
		if Time.now > borrow_book.return_date
			(Time.now.to_date - borrow_book.return_date.to_date).to_i
		else
			0
		end
	end

	def amount_borrow_books
		borrow_books = Array.new

		BorrowBook.all.map {|bb| borrow_books << bb if bb.return_book.blank? }

		return borrow_books.count
	end

	def count_current_book(book)
		borrowed = BorrowBook.where('book_id = ? AND return_status = true', book.id).count
		book.exptotal - borrowed
	end
end

app/helpers/book_types_helper.rb
module BookTypesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrow_books_helper.rb
module BorrowBooksHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/guest_books_helper.rb
module GuestBooksHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/return_books_helper.rb
module ReturnBooksHelper
end

app/helpers/theses_helper.rb
module ThesesHelper
end

app/views/shared/_breadcumb.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <%= params[:controller].gsub("_", " ").titleize rescue "" %>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><%= params[:controller] %></li>
  </ol>
</section>

app/views/shared/_form_popup_container.html.erb
<div class="modal fade" id="FormContainer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Data</h4>
      </div>
	  <div id='model-content'>
	  </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="#" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>FIKI</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">PERPUSTAKAAN FAKULTAS</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag "icons/avatar.png", class: "user-image", alt: "User Image" %>
            <span class="hidden-xs"><%= current_user.email %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <%= image_tag "icons/avatar.png", class: "img-circle", alt: "User Image" %>
              <p>
                <%= current_user.email %>
                <small>Last Login: <%= current_user.current_sign_in_at %></small>
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-default btn-flat" %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_notice.html.erb
<% unless notice.blank? %>
	<div class="alert alert-success alert-dismissable">
	  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	  <%= notice %>
	</div>
<% end %>

app/views/shared/_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag "icons/avatar.png", class: "img-circle", alt: "User Image" %>
      </div>
      <div class="pull-left info">
        <br/>
        <p><%= current_user.email %></p>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li>
        <%= link_to root_url do %>
          <i class="fa fa-home"></i> <span>Home</span>
        <% end %>
      </li>
      <li>
        <%= link_to dashboard_index_path do %>
          <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        <% end %>
      </li>
      <li>
        <%= link_to members_url do %>
          <i class="fa fa-users"></i> <span>Anggota</span>
        <% end %>
      </li>
      <li>
        <%= link_to "#", class: 'treeview' do %>
          <i class="fa fa-book"></i>
          <span>Buku</span>
          <i class="fa fa-angle-left pull-right"></i>
        <% end %>

		    <ul class="treeview-menu" style="display: none;">
          <li>
            <%= link_to books_url, class: 'treeview' do %>
              <i class="fa fa-circle-o"></i> <span>Data Buku</span>
            <% end %>
          </li>
          <li>
            <%= link_to book_types_url, class: 'treeview' do %>
              <i class="fa fa-circle-o"></i> <span>Tipe Buku</span>
            <% end %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to theses_url do %>
          <i class="fa fa-book"></i> <span>Skripsi & Laporan</span>
        <% end %>
      </li>
      <li>
        <%= link_to "#", class: 'treeview' do %>
          <i class="fa fa-exchange"></i>
          <span>Transaksi</span>
          <i class="fa fa-angle-left pull-right"></i>
        <% end %>

        <ul class="treeview-menu" style="display: none;">
          <li>
            <%= link_to borrow_books_url, class: 'treeview' do %>
              <i class="fa fa-circle-o"></i> <span>Peminjaman</span>
            <% end %>
          </li>
          <li>
            <%= link_to return_books_path, class: 'treeview' do %>
              <i class="fa fa-circle-o"></i> <span>Pengembalian</span>
            <% end %>
          </li>
        </ul>
      </li>
      <li>
      <%= link_to guest_books_url do %>
          <i class="fa fa-book"></i>
          <span>Buku Tamu</span>
        <% end %>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>