config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'catalogs#index'

  resources :catalogs, only: [:index] do
  end

  resources :guest_books do
    collection do
      get 'search'
    end
  end

  resources :book_types do
    collection do
      get 'search'
    end
  end

  resources :books do
    member do
      get 'generate_barcode'
    end
    collection do
      get 'search'
    end
  end

  resources :catalogs do
    collection do
      get 'search'
    end
  end

  resources :dashboard, only: [:index]

  resources :theses do
    collection do
      get 'search'
    end
  end

  resources :members do
    member do
      get 'generate_card'
    end
    collection do
      get 'search'
      get 'download'
    end
  end

  resources :return_books, only: [:index] do
    collection do
      get 'search'
    end
  end

  resources :borrow_books, only: [:index, :new, :create] do
    resources :return_books

    collection do
      get 'search'
      get 'validate_borrow_books'
      get 'validate_return_date'
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader

	belongs_to	:book_type

	has_many :borrow_books

	scope :searching, lambda{ |query| where("book_code like :keyword OR title like :keyword OR author like :keyword OR publisher like :keyword OR yop like :keyword OR resource like :keyword", { keyword: "%#{query}%" }) unless query.blank? }

	validates :isbn, length: { minimum: 13, maximum: 13 }

	after_create :prepare_number

	def prepare_number
		BookNumber.generate_number(self)
	end

	def generate_barcode
		require 'barby/barcode/code_128'
		require 'barby/outputter/cairo_outputter'

		barcode = Barby::Code128B.new(self.isbn)
		save_path = Rails.root.join('public', 'downloads', 'barcode', 'books',"#{self.isbn}.png")
		File.open(save_path, 'w'){|f| f.write barcode.to_png }
	end
end

app/models/book_type.rb
class BookType < ActiveRecord::Base
	has_many :books
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :generate_barcode]
  before_action :set_book_type, only: [:index, :edit]

  def index
    @books = Book.all.order('id desc').page(params[:page]).per(params[:per_page])
    @book = Book.new
  end

  def search
    @books = Book.searching(params[:keywords])
  end

  def generate_barcode
    @book.generate_barcode

    redirect_to "/downloads/barcode/books/#{@book.isbn}.png"
  end

  def new
    @book = Book.new
  end

  def edit
    render layout: false
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_url, notice: 'Buku berhasil ditambahkan.' }
      else
        format.html { redirect_to books_url, notice: 'Buku tidak berhasil ditambahkan.' }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to books_url, notice: 'Buku berhasil dirubah.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Buku berhasil dihapus.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def set_book_type
      @book_types = BookType.all.map {|type| [type.name, type.id] }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_code, :title, :class_no, :subject, :author, :publisher, :yop, :city, :language, :book_type_id, :price, :attachment, :borrow_amount, :read_amount, :ref_amount, :exptotal, :isbn, :resource)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/shared/_form_popup.html.erb
<div class="modal fade" id="Add" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel">Tambah Data</h3>
      </div>
	  <%= form_for @book, html: { class: 'form-group' } do |f| %>
		<div class="modal-body">
		  <h4>DATA BUKU</h4><br/>
		      <div class="row">
            <%= f.label :isbn, 'ISBN', class: 'col-xs-3' %>
            <div class="col-xs-6">
              <%= f.text_field :isbn, class: 'form-control', pattern: ".{13,13}", maxlength: 13, title: "ISBN harus berisi 13 karakter" %>
            </div>
          </div>
          <div class="row">
            <%= f.label :title, 'Judul', class: 'col-xs-3' %>
            <div class="col-xs-6">
              <%= f.text_field :title, class: 'form-control', required: true %>
            </div>
          </div>
          <div class="row">
            <%= f.label :book_type_id, 'Tipe Buku', class: 'col-xs-3' %>
            <div class="col-xs-3">
              <%= f.select :book_type_id, options_for_select(@book_types), {}, class: "form-control", required: true %>
            </div>
          </div>
		  <div class="row">
            <%= f.label :language, 'Bahasa', class: 'col-xs-3' %>
            <div class="col-xs-3">
              <%= f.text_field :language, class: 'form-control' %>
            </div>
          </div>
		  <div class="row">
            <%= f.label :attachment, 'Cover', class: 'col-xs-3' %>
            <div class="col-xs-9">
              <%= f.file_field :attachment, class: 'form-control' %>
            </div>
          </div>
          <div class="row">
            <%= f.label :class_no, 'No Rak', class: 'col-xs-3' %>
            <div class="col-xs-3">
              <%= f.text_field :class_no, class: 'form-control' %>
            </div>
          </div>
		      <!-- <div class="row">
            <%#= f.label :borrow_amount, 'Dipinjamkan', class: 'col-xs-3' %>
            <div class="col-xs-4">
              <%#= f.text_field :borrow_amount, class: 'form-control' %>
            </div>
          </div>
          <div class="row">
            <%#= f.label :read_amount, 'Dibaca', class: 'col-xs-3' %>
            <div class="col-xs-4">
              <%#= f.text_field :read_amount, class: 'form-control' %>
            </div>
          </div> -->
          <!-- <div class="row">
            <%#= f.label :ref_amount, 'Jumlah Ref', class: 'col-xs-3' %>
            <div class="col-xs-4">
              <%#= f.text_field :ref_amount, class: 'form-control' %>
            </div>
          </div> -->
          <div class="row">
            <%= f.label :exptotal, 'Jumlah Buku', class: 'col-xs-3' %>
            <div class="col-xs-4">
              <%= f.text_field :exptotal, class: 'form-control' %>
            </div>
          </div>
		      <div class="row">
            <%= f.label :resource, 'Asal Buku', class: 'col-xs-3' %>
            <div class="col-xs-6">
              <%= f.text_field :resource, class: 'form-control' %>
            </div>
          </div>
          <!-- <div class="row">
            <%#= f.label :subject, 'Subjek', class: 'col-xs-3' %>
            <div class="col-xs-6">
              <%#= f.text_field :subject, class: 'form-control' %>
            </div>
          </div> -->

		  <hr>

		  <h4>DATA PENGARANG & PENERBIT</h4><br/>
          <div class="row">
            <%= f.label :author, 'Pengarang', class: 'col-xs-3' %>
            <div class="col-xs-6">
              <%= f.text_field :author, class: 'form-control' %>
            </div>
          </div>
          <div class="row">
            <%= f.label :publisher, 'Penerbit', class: 'col-xs-3' %>
            <div class="col-xs-6">
              <%= f.text_field :publisher, class: 'form-control' %>
            </div>
          </div>
          <div class="row">
            <%= f.label :yop, 'Tahun Terbit', class: 'col-xs-3' %>
            <div class="col-xs-3">
              <%= f.text_field :yop, class: 'form-control' %>
            </div>
          </div>
          <div class="row">
            <%= f.label :city, 'Kota', class: 'col-xs-3' %>
            <div class="col-xs-3">
              <%= f.text_field :city, class: 'form-control' %>
            </div>
          </div>
          <!-- <div class="row">
            <%#= f.label :price, 'Harga', class: 'col-xs-3' %>
            <div class="col-xs-4">
              <%#= f.text_field :price, class: 'form-control' %>
            </div>
          </div> -->
		</div>
		<div class="modal-footer">
		  <div class="row">
			<div class="col-xs-2 pull-right">
			  <input type="submit" value="Tambah" class="btn btn-primary">
			</div>
		  </div>
		</div>
	  <% end %>
    </div>
  </div>
</div>

app/views/books/shared/_list.html.erb
<div class="col-sm-12">
  <% unless @books.blank? %>
    <table class="table table-bordered table-striped dataTable" role="grid">
      <thead>
        <tr>
          <% if !current_user.blank? && params[:controller] == "books" %>
            <th><input type="checkbox"></th>
          <% end %>
          <th>Kode Buku</th>
          <th>Judul</th>
          <th>Pengarang</th>
      		<% if !current_user.blank? && params[:controller] == "books" %>
      			<th>Penerbit</th>
      			<th>Tahun</th>
      			<th>Sumber</th>
      			<th colspan="3"></th>
          <% else %>
            <th>No Rak</th>
            <th>Jumlah Buku</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <% if !current_user.blank? && params[:controller] == "books" %>
              <td><%= check_box_tag :book_code, book.book_code %></td>
            <% end %>
            <td><%= book.book_code %></td>
            <td><%= book.title %></td>
            <td><%= book.author %></td>
      		  <% if !current_user.blank? && params[:controller] == "books" %>
        			<td><%= book.publisher %></td>
        			<td><%= book.yop %></td>
        			<td><%= book.resource %></td>
              <td>
                <%= link_to 'Detail', 'javascript:void(0)', class: "btn btn-primary btn-detail-#{book.id}", onclick: "CallDetail('#{book.id}')" %>
                <%= link_to '#', onclick: "CallContent('#{edit_book_path(book)}')", class: "btn btn-primary" do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <%= link_to book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
                  <i class="fa fa-trash-o"></i>
                <% end %>
                <%= link_to generate_barcode_book_path(book), id: 'AddBtn', class: "btn btn-success", target: "_blank" do %>
                  <i class="fa fa-barcode"></i>
                <% end %>
              </td>
            <% else %>
              <td><%= book.class_no %></td>
              <td><%= count_current_book(book) %></td>
            <% end %>
          </tr>
          <% if !current_user.blank? && params[:controller] == "books" %>
            <tr class="detail-<%= book.id %> hide">
              <td colspan="10">
                <!-- <div class="container"> -->
                  <div class="row">
                    <div class="col-xs-6">
                      <fieldset>
                        <legend>Data Buku</legend>
                        <div class="row">
                          <label class="col-xs-3">Kode Buku</label>
                          <div class="col-xs-9">
                            <%= book.book_code %>
                          </div>
                        </div>
                        <div class="row">
                          <label class="col-xs-3">ISBN</label>
                          <div class="col-xs-9">
                            <%= book.isbn %>
                          </div>
                        </div>
                        <div class="row">
                          <label class="col-xs-3">Judul Buku</label>
                          <div class="col-xs-9">
                            <%= book.title %>
                          </div>
                        </div>
                        <div class="row">
                          <label class="col-xs-3">Jenis Buku</label>
                          <div class="col-xs-9">
                            <%= book.book_type.name %>
                          </div>
                        </div>
                        <div class="row">
                          <label class="col-xs-3">No Rak</label>
                          <div class="col-xs-9">
                            <%= book.class_no %>
                          </div>
                        </div>
                        <div class="row">
                          <label class="col-xs-3">Bahasa</label>
                          <div class="col-xs-9">
                            <%= book.language %>
                          </div>
                        </div>
                        <div class="row">
                          <label class="col-xs-3">Jumlah Buku</label>
                          <div class="col-xs-9">
                            <%= book.exptotal %> (Exemplar)
                          </div>
                        </div>
                        <div class="row">
                          <label class="col-xs-3">Sumber</label>
                          <div class="col-xs-9">
                            <%= book.resource %>
                          </div>
                        </div>
                      </fieldset>
                      <br/>
                      <fieldset>
                        <legend>Data Pengarang & Penerbit</legend>
                        <div class="row">
                          <label class="col-xs-3">Pengarang</label>
                          <div class="col-xs-9">
                            <%= book.author %>
                          </div>
                        </div>
                        <div class="row">
                          <label class="col-xs-3">Penerbit</label>
                          <div class="col-xs-9">
                            <%= book.publisher %>
                          </div>
                        </div>
                        <div class="row">
                          <label class="col-xs-3">Tahun Terbit</label>
                          <div class="col-xs-9">
                            <%= book.yop %>
                          </div>
                        </div>
                        <div class="row">
                          <label class="col-xs-3">Kota</label>
                          <div class="col-xs-9">
                            <%= book.city %>
                          </div>
                        </div>
                        <div class="row">
                          <label class="col-xs-3">Tahun Terbit</label>
                          <div class="col-xs-9">
                            <%= book.yop %>
                          </div>
                        </div>
                      </fieldset>

                    </div>
                    <div class="col-xs-3 pull-right">
                      <br/>
                      <%= image_tag book.attachment.url, class: "img-responsive img-thumbnail" %>
                    </div>
                  </div>
                <!-- </div> -->
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <% if !current_user.blank? && params[:controller] == "books" %>
            <th><input type="checkbox"></th>
          <% end %>
          <th>Kode Buku</th>
          <th>Judul</th>
          <th>Pengarang</th>
          <% if !current_user.blank? && params[:controller] == "books" %>
      			<th>Penerbit</th>
      			<th>Tahun</th>
      			<th>Sumber</th>
      			<th colspan="3"></th>
          <% else %>
            <th>No Rak</th>
            <th>Jumlah Buku</th>
          <% end %>
        </tr>
      </tfoot>
    </table>
  <% else %>
    <p><%= !current_user.blank? && params[:controller] == "books" ? "Tidak ada data" : "Data tidak ditemukan" %></p>
  <% end %>
</div>