config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'catalogs#index'

  resources :catalogs, only: [:index] do
  end

  resources :guest_books do
    collection do
      get 'search'
    end
  end

  resources :book_types do
    collection do
      get 'search'
    end
  end

  resources :books do
    member do
      get 'generate_barcode'
    end
    collection do
      get 'search'
    end
  end

  resources :catalogs do
    collection do
      get 'search'
    end
  end

  resources :dashboard, only: [:index]

  resources :theses do
    collection do
      get 'search'
    end
  end

  resources :members do
    member do
      get 'generate_card'
    end
    collection do
      get 'search'
      get 'download'
    end
  end

  resources :return_books, only: [:index] do
    collection do
      get 'search'
    end
  end

  resources :borrow_books, only: [:index, :new, :create] do
    resources :return_books

    collection do
      get 'search'
      get 'validate_borrow_books'
      get 'validate_return_date'
    end
  end

end

app/models/member.rb
class Member < ActiveRecord::Base
	CONTAINER_DIR = File.join(Rails.public_path, "downloads")

	has_many :borrow_books

	scope :searching, lambda{ |query| where("nim like :keyword OR firstname like :keyword OR lastname like :keyword", { keyword: "%#{query}%" }) unless query.blank? }

	def self.import_all
		unless File.directory? CONTAINER_DIR #~> check if container dir exist
	      Dir.mkdir CONTAINER_DIR, 0755
	    end

		require 'spreadsheet'

		Spreadsheet.client_encoding = 'UTF-8'

		members_file = Spreadsheet::Workbook.new
		members_file_sheet1 = members_file.create_worksheet

		members_file_sheet1[0,0] = "NIM"
		members_file_sheet1[0,1] = "Nama"
		members_file_sheet1[0,2] = "Tempat Lahir"
		members_file_sheet1[0,3] = "Tanggal Lahir"
		members_file_sheet1[0,4] = "Jenis Kelamin"
		members_file_sheet1[0,5] = "Alamat"
		members_file_sheet1[0,6] = "Telepon"
		members_file_sheet1[0,7] = "Masa Aktif"
		members_file_sheet1[0,8] = "Status"

		index = 1
		Member.all.each do |member|
			members_file_sheet1[index,0] = member.nim
			members_file_sheet1[index,1] = "#{member.firstname} #{member.lastname}"
			members_file_sheet1[index,2] = member.pob
			members_file_sheet1[index,3] = member.dob
			members_file_sheet1[index,4] = member.gender
			members_file_sheet1[index,5] = member.address
			members_file_sheet1[index,6] = member.phone
			members_file_sheet1[index,7] = member.active_period
			members_file_sheet1[index,8] = member.status? ? "Aktif" : "Non Aktif"

			index += 1
		end

		path_file = File.join(CONTAINER_DIR, "daftar_anggota.xls")
		members_file.write path_file
	end

	def generate_barcode
		require 'barby/barcode/code_128'
		require 'barby/outputter/cairo_outputter'

		barcode = Barby::Code128B.new(self.nim)
		save_path = Rails.root.join('public', 'downloads', 'barcode', 'members',"#{self.nim}.png")
		File.open(save_path, 'w'){|f| f.write barcode.to_png }
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	before_action :set_member, only: [:show, :edit, :update, :destroy, :generate_card]
	before_action :gender_option, only: [:index, :edit]
  before_action :prepare_barcode, only: [:generate_card]

  def index
    @members = Member.all.order('id desc').page(params[:page]).per(params[:per_page])
    @member = Member.new
  end

  def search
    @members = Member.searching(params[:keywords])
  end

  def download
    generate_file = Member.import_all
    redirect_to "/downloads/daftar_anggota.xls"
  end

  def generate_card
    html = render_to_string template: "members/card.html.erb", layout: "pdf", locals: { member: @member}
    pdf = WickedPdf.new.pdf_from_string(html)
    save_path = Rails.root.join('public', 'downloads', 'pdfs',"#{@member.nim}.pdf")
    File.open(save_path, 'wb') do |file|
      file << pdf
    end

    redirect_to "/downloads/pdfs/#{@member.nim}.pdf"
  end

  def new
    @member = Member.new
  end

  def edit
    render layout: false
  end

  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to members_url, notice: 'Anggota berhasil ditambahkan.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to members_url, notice: 'Anggota berhasil diubah.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Anggota berhasil dihapus.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    def prepare_barcode
      @member.generate_barcode
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def member_params
      params.require(:member).permit(:nim, :firstname, :lastname, :pob, :dob, :gender, :address, :phone, :active_period, :status)
	end

	def gender_option
		@gender = [['Laki-Laki', 'L'],['Perempuan', 'P']]
	end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/shared/_form_popup.html.erb
<div class="modal fade" id="Add" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel">Tambah Data</h3>
      </div>
      <%= form_for @member, html: { class: 'form-group' } do |f| %>
        <div class="modal-body">
          <div class="row">
            <%= f.label :nim, 'NIM', class: 'col-xs-3' %>
            <div class="col-xs-4">
              <%= f.text_field :nim, class: 'form-control' %>
            </div>
          </div>
          <div class="row">
            <%= f.label :firstname, 'Nama Depan', class: 'col-xs-3' %>
            <div class="col-xs-9">
              <%= f.text_field :firstname, class: 'form-control' %>
            </div>
          </div>
          <div class="row">
            <%= f.label :lastname, 'Nama Belakang', class: 'col-xs-3' %>
            <div class="col-xs-9">
              <%= f.text_field :lastname, class: 'form-control' %>
            </div>
          </div>
          <div class="row">
            <%= f.label :pob, 'Tempat Lahir', class: 'col-xs-3' %>
            <div class="col-xs-9">
              <%= f.text_field :pob, class: 'form-control' %>
            </div>
          </div>
          <div class="row">
            <%= f.label :dob, 'Tanggal Lahir', class: 'col-xs-3' %>
            <div class="col-xs-4">
              <div class="input-group">
                <div class="input-group-addon">
                  <i class="fa fa-calendar"></i>
                </div>
                <%= f.text_field :dob, class: 'form-control', 'data-inputmask' => "'alias': 'yyyy/mm/dd'", 'data-mask' => "" %>
              </div>
            </div>
          </div>
          <div class="row">
            <%= f.label :gender, 'Jenis Kelamin', class: 'col-xs-3' %>
            <div class="col-xs-9">
              <%= f.select :gender, options_for_select(@gender), {}, class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <%= f.label :address, 'Alamat', class: 'col-xs-3' %>
            <div class="col-xs-9">
              <%= f.text_area :address, class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <%= f.label :phone, 'Telepon', class: 'col-xs-3' %>
            <div class="col-xs-9">
              <div class="input-group">
                <div class="input-group-addon">
                  <i class="fa fa-phone"></i>
                </div>
                <%= f.text_field :phone, class: 'form-control', 'data-inputmask' => "'mask': ['9999999999[99999]', '+099 99 99 9999[9]-9999']", 'data-mask' => "" %>
              </div>
            </div>
          </div>
          <div class="row">
            <%= f.label :active_period, 'Masa Aktif', class: 'col-xs-3' %>
            <div class="col-xs-4">
              <div class="input-group">
                <div class="input-group-addon">
                  <i class="fa fa-calendar"></i>
                </div>
                <%= f.text_field :active_period, value: (Time.now + (4).years), class: 'form-control', 'data-inputmask' => "'alias': 'yyyy/mm/dd'", 'data-mask' => "" %>
              </div>
            </div>
          </div>
          <div class="row">
            <%= f.label :status, 'Active', class: 'col-xs-3' %>
            <div class="col-xs-3">
              <%= f.check_box :status, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="row">
            <div class="col-xs-2 pull-right">
              <input type="submit" value="Tambah" class="btn btn-primary">
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/members/shared/_list.html.erb
<div class="col-sm-12">
  <table class="table table-bordered table-striped dataTable" role="grid">
    <thead>
      <tr>
        <th><input type="checkbox"></th>
        <th>NIM</th>
        <th>Nama</th>
        <th>Telepon</th>
        <th>Masa Aktif</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= check_box_tag :id, member.id %></td>
          <td><%= member.nim %></td>
          <td><%= member.firstname %> <%= member.lastname %></td>
          <td><%= member.phone %></td>
          <td><%= member.active_period %></td>
          <td><%= member.status ? 'Aktif' : 'Non Aktif' %></td>
          <td>
            <%= link_to 'Detail', 'javascript:void(0)', class: "btn btn-primary btn-detail-#{member.id}", onclick: "CallDetail('#{member.id}')" %>

            <%= link_to '#', onclick: "CallContent('#{edit_member_path(member)}')", class: 'btn btn-primary' do %>
              <i class="fa fa-edit"></i>
            <% end %>

            <%= link_to member, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
              <i class="fa fa-trash-o"></i>
            <% end %>

            <%= link_to generate_card_member_path(member), id: 'AddBtn', class: "btn btn-success", target: "_blank" do %>
              <i class="fa fa-print"></i>
            <% end %>
          </td>
        </tr>
        <tr class="detail-<%= member.id %> hide">
          <td colspan="10">
            <div class="row">
              <div class="col-xs-9">
                <h4><%= member.firstname %> <%= member.lastname %></h4>
                <hr>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-9">
                <div class="row">
                  <div class="col-xs-6">
                    <div class="row">
                      <label class="col-xs-3">NIM</label>
                      <div class="col-xs-9">
                        <%= member.nim %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-6">
                    <div class="row">
                      <label class="col-xs-3">Tempat Lahir</label>
                      <div class="col-xs-9">
                        <%= member.pob %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-6">
                    <div class="row">
                      <label class="col-xs-3">Tanggal Lahir</label>
                      <div class="col-xs-9">
                        <%= member.dob %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-6">
                    <div class="row">
                      <label class="col-xs-3">Jenis Kelamin</label>
                      <div class="col-xs-9">
                        <%= member.gender %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-6">
                    <div class="row">
                      <label class="col-xs-3">Alamat</label>
                      <div class="col-xs-9">
                        <%= member.address %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-6">
                    <div class="row">
                      <label class="col-xs-3">Telepon</label>
                      <div class="col-xs-9">
                        <%= member.phone %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-6">
                    <div class="row">
                      <label class="col-xs-3">Masa Aktif</label>
                      <div class="col-xs-9">
                        <%= member.active_period %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xs-2">
              <%= link_to 'Cetak Kartu Anggota', generate_card_member_path(member), id: 'AddBtn', class: "btn btn-success" %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <th><input type="checkbox"></th>
        <th>NIM</th>
        <th>Nama</th>
        <th>Telepon</th>
        <th>Masa Aktif</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </tfoot>
  </table>
</div>